### ISSUE TITLE
Unclear that this is just a wrapper for a hosted-editor

### ISSUE THREAD

**Issue by bradvogel** [unroll-io/react-email-editor#2]
It's not clear in the readme that this is just a wrapper for a proprietary UI hosted on a third party. Does the MIT license apply to that editor too?

**Comment by adeelraza** [comment]
@bradvogel It's a wrapper component for Unroll.io's embeddable editor. But you make a good point. I just updated the readme to make it clear that its a wrapper component. MIT license applies to this component only.

**Comment by davidfurlong** [comment]
README is still not clear enough `wrapper component` is not obvious. Disappointed

**Comment by adeelraza** [comment]
@davidfurlong the library is not limited by pricing or having an Unlayer account. Both the things are optional, only required if you need additional features. Everything from loading a design, to exporting HTML works as expected without paying or having an account.
